In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
df= pd.read_csv("C:/Users/gupta/Documents/GitHub/Last-Mile-Delivery-Delay-Root-Cause-Analysis/data/Raw/train.csv")
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

In [4]:
df.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition
count,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702,1.023359
std,8.185109,22.883647,7.335122,21.118812,0.839065
min,-30.905562,-88.366217,0.010000,0.010000,0.000000
25%,12.933284,73.170000,12.988453,73.280000,0.000000
50%,18.546947,75.898497,18.633934,76.002574,1.000000
75%,22.728163,78.044095,22.785049,78.107044,2.000000
max,30.914057,88.433452,31.054057,88.563452,3.000000

In [5]:
def haversine(lat1,lon1,lat2,lon2):
    R=6371 #earth radius

    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    
    return R * c

In [6]:
df['Distance from Hub'] = haversine(
    df['Restaurant_latitude'],
    df['Restaurant_longitude'],
    df['Delivery_location_latitude'],
    df['Delivery_location_longitude']
).round(2)

print(df['Distance from Hub'].describe())

count    45593.000000
mean        99.303929
std       1099.731299
min          1.470000
25%          4.660000
50%          9.260000
75%         13.760000
max      19692.670000
Name: Distance from Hub, dtype: float64

In [ ]:
# ── Fix dtypes first (your columns are 'object' type) ───
df['Delivery_person_Age']     = pd.to_numeric(df['Delivery_person_Age'], errors='coerce')
df['Delivery_person_Ratings'] = pd.to_numeric(df['Delivery_person_Ratings'], errors='coerce')
df['multiple_deliveries']     = pd.to_numeric(df['multiple_deliveries'], errors='coerce')
df['Time_taken(min)']         = df['Time_taken(min)'].str.extract(r'(\d+)').astype(int)
# ↑ Important — this column often loads as "(min) 24" string format

# ── Experience column from Age ───────────────────────────
df['Experience'] = df['Delivery_person_Age'].apply(
    lambda x: 'Junior' if x < 25 else 'Senior'
)

# ── Efficiency Ratio (core RCA metric) ──────────────────
df['Minutes_Per_KM'] = (df['Time_taken(min)'] / df['Distance from Hub']).round(2)

# ── Expected time & Delay ────────────────────────────────
df['Expected_Time'] = df.groupby(
    ['City', 'Road_traffic_density']
)['Time_taken(min)'].transform('median')

df['Delay_Minutes'] = (df['Time_taken(min)'] - df['Expected_Time']).round(1)
df['On_Time']       = (df['Delay_Minutes'] <= 0).astype(int)

# ── Courier Success Rate ─────────────────────────────────
success = df.groupby('Delivery_person_ID')['On_Time'].mean().reset_index()
success.columns = ['Delivery_person_ID', 'Success_Rate']
df = df.merge(success, on='Delivery_person_ID')

# ── Save cleaned file ────────────────────────────────────
df.to_csv('C:/Users/gupta/Documents/GitHub/Last-Mile-Delivery-Delay-Root-Cause-Analysis/data/processed/deliveries_clean.csv', index=False)

In [18]:
df['Time_taken(min)'].head()

0    24.0
1    33.0
2    26.0
3    21.0
4    30.0
Name: Time_taken(min), dtype: float64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          43739 non-null  float64
 3   Delivery_person_Ratings      43685 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          44600 non-null  float64
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  float64
 20  Distance from Hub            45593 non-null  float64
 21  Experience                   45593 non-null  object
 22  Minutes_Per_KM               45593 non-null  float64
 23  Expected_Time                45593 non-null  float64
 24  Delay_Minutes                45593 non-null  float64
 25  On_Time                      45593 non-null  int64
 26  Success_Rate_x               45593 non-null  float64
 27  Success_Rate_y               45593 non-null  float64
 28  Success_Rate                 45593 non-null  float64
dtypes: float64(15), int64(2), object(12)
memory usage: 10.1+ MB

In [ ]:
df.drop(columns=['ID', 'Expected_Time', 'Success_Rate_x', 'Success_Rate_y'], inplace=True)

print(df.shape)      
print(df.columns.tolist())

(45593, 25)
['Delivery_person_ID', 'Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude', 'Restaurant_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude', 'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density', 'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)', 'Distance from Hub', 'Experience', 'Minutes_Per_KM', 'Delay_Minutes', 'On_Time', 'Success_Rate']

In [22]:
df.isnull().sum()

Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                          0
City                              0
Time_taken(min)                   0
Distance from Hub                 0
Experience                        0
Minutes_Per_KM                    0
Delay_Minutes                     0
On_Time                           0
Success_Rate                      0
dtype: int64

In [23]:
df['Delivery_person_Age'].fillna(df['Delivery_person_Age'].median(), inplace=True)
df['Delivery_person_Ratings'].fillna(df['Delivery_person_Ratings'].median(), inplace=True)
df['multiple_deliveries'].fillna(df['multiple_deliveries'].mode()[0], inplace=True)

df.isnull().sum().sum()

np.int64(0)

In [24]:
df.to_csv('C:/Users/gupta/Documents/GitHub/Last-Mile-Delivery-Delay-Root-Cause-Analysis/data/processed/final_deliveries_clean.csv', index=False)